image: maven:3.9.4-eclipse-temurin-17

stages:
  - linter
  - test
  - build

lint:
  stage: linter
  script:
    - mvn checkstyle:check
  allow_failure: true

unit_tests:
  stage: test
  script:
    - mvn test --fail-at-end
  coverage: '/Total.*?(\d+)%/'